[gcp_service_account]
type = "service_account"
project_id = "announcement-system-460807"
private_key_id = "bec1e480c54c9032c3c23a4b835ec2a8094526ee"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDNfSFp9Pbi0RrH
vF+wCiN07cv9YBsm1ciNE12vOX3y5ewh2kB/ikvEX7Klop99O/OcA23PyV45jpdI
FF4sJrv/zI3fB7725n6whxQidtOsoDYN9fpKfOAWfT0mwmku8gnGJKQeQxAULApl
wpEqc/Wc8ZdsYIpxLHD2mFCE+9kRlXPV8jBZn6npuqqELd2JNyTy8N27nni17We/
gA2LqY/Jru4G/f6Lrfl6FcoiRTUNxi6OLTwLxvhTuFzqTFh+JlbjKe2uJdOfs0mq
BuHwFtFNHo0pkM5GRjwxJDpVTQEf+aDFP8JR9+Gzo0VsHecYB0Jvz31y9prYrPWq
YJSsg73nAgMBAAECggEAYXZ0HrldT/814H5sNCba4l7XXfnzZtwHH0KMMMvn/Qko
knXeGaASh7WMGhuj4dZJmTnXH7K2yj3jawCeGfrVOGJg9+PIo3p3pGqtFhueEkZ6
3OxKJoJMFt6X3oZfNTD/icdfQCs2uRqaY+GA0M3nNOUxmOnBQCR//7YGmsyJDFko
2lpbaXyCPs/jF/z3XKcdX0V6VZia7VFa3FVNNy1q39P2sHCPA6OKlCfE8gm9PNvc
dI1rZ2dNBUYvJpV2/ca7xTL7OjSmuezughzTZmI1kag8dd7PqcHR5rs+OGgeKhVh
+TYw4jiGNAOApDv/W8bIv9uP7i+ReLTI0TjZpylhoQKBgQDpGh7LudRaf+gmLjDM
ZnHKBIqmmXIJFBGGFSDUrZXMihZZL6t78XCk4rJs76Hq7mk7JjljMO+3UqyQ4Dvz
1GSHGT2/4J3acEsqQ1KCWYSEIsXZYG1NC8kiOFJlI5x1nIxRnhSRibDY7gi2ITx0
j9wRnJPnr70jcHY+mWPHIY2lvQKBgQDhrJzTLqK6BcHEJcJvCv+lyoA6I5Df/CdA
7DlCUXRu+FEj6MFeKnnUFU9TXawXXnCbYQThBJccRJX02W9jSSdtlhShIGI++Fyf
OlX6sLcIg2jTsKsFB1lUA1GtPLTOb3eesF/7HWP815OadlwyQxHR/lHSwjUWfI3N
x86xJVcScwKBgFcPT2Mtg5dNYEoqREWDGYqnCZXRh5rGaQkYCQwFzQX4qQIkYLrI
4RZkKNmw4luZMapKy3I1i8J/WT4+0YVu1SD0F3D7lllISXp+bGmMv4aOajCW6Bu3
hCaIvJVTqJLwpiOxk+MLdwZ+WLiVTzwFot7dCQymQVDkJvWYWoC8EmhNAoGADZE3
DGstVUmrUIOEoPBkVi9KbjRdLVoXcgvBlX8YJOPA3QvNNEARevKdBkIHapA+7Nh0
VqLUAtsMuN+plqp7OFdhfh5YSbjcuKXlLWEaX+SmlLN2VKMQd8CLVILly9NfuaaY
3pvxuu2q7gpXmJ33oExN1wHd9zAdxlVQ082O4okCgYEAhaSIS6RmzvcHp6wgvICU
K+9E44pex/MyJPn394dPbcTEyqx1HSoXlA6J/frOZAnAA0VOzsYtivd11kXLSjvq
Dc/9ZUbQIpQKg6JXBT50FgTR19WMOg6h/um+n53McHkbpTczSDEiTcIoxvqHbiK3
RShIN1GFF8fYx5wA5mVMKRU=
-----END PRIVATE KEY-----"""
client_email = "gspread-access@announcement-system-460807.iam.gserviceaccount.com"
client_id = "113672114111830674409"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/gspread-access%40announcement-system-460807.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
